 import 'Auth_model.dart';
import 'Scedules_model.dart';

class BookingModel{
  int? id;
  String? patId;
  int? scdId;
  String? state;
  ScadulesModel? schedule;


     BookingModel.fromJson(Map<String,dynamic>json)
     {
       id = json['id'];
       patId = json['patId'];
       scdId = json['scdId'];
       state = json['state'];
      schedule = json['schedule'] != null ? ScadulesModel.fromjson(json['data'] ):null;


     }




 }

 class Autogenerated {
   int? id;
   String? patId;
   int? scdId;
   Schedule? schedule;
   String? state;

   Autogenerated({this.id, this.patId, this.scdId, this.schedule, this.state});

   Autogenerated.fromJson(Map<String, dynamic> json) {
     id = json['id'];
     patId = json['patId'];
     scdId = json['scdId'];
     schedule = json['schedule'] != null
         ? new Schedule.fromJson(json['schedule'])
         : null;
     state = json['state'];
   }

   Map<String, dynamic> toJson() {
     final Map<String, dynamic> data = new Map<String, dynamic>();
     data['id'] = this.id;
     data['patId'] = this.patId;
     data['scdId'] = this.scdId;
     if (this.schedule != null) {
       data['schedule'] = this.schedule!.toJson();
     }
     data['state'] = this.state;
     return data;
   }
 }

 class Schedule {
   int? id;
   String? dateOnly;
   String? dayName;
   String? startTime;
   String? endTime;
   String? availability;

   Schedule(
       {this.id,
         this.dateOnly,
         this.dayName,
         this.startTime,
         this.endTime,
         this.availability});

   Schedule.fromJson(Map<String, dynamic> json) {
     id = json['id'];
     dateOnly = json['dateOnly'];
     dayName = json['dayName'];
     startTime = json['startTime'];
     endTime = json['endTime'];
     availability = json['availability'];
   }

   Map<String, dynamic> toJson() {
     final Map<String, dynamic> data = new Map<String, dynamic>();
     data['id'] = this.id;
     data['dateOnly'] = this.dateOnly;
     data['dayName'] = this.dayName;
     data['startTime'] = this.startTime;
     data['endTime'] = this.endTime;
     data['availability'] = this.availability;
     return data;
   }
 }