
 class ScadulesModel{
  int? id;
  String? dateOnly;
  String? dayName;
  String? startTime;
  String? endTime;
  String? availability;


  ScadulesModel({
   required this.id,
   required this.dateOnly,
   required this.dayName,
   required this.startTime,
   required this.endTime,
   required this.availability,
  });


  factory ScadulesModel.fromjson(jsonData){
   return ScadulesModel(
    id: jsonData['id'],
    dateOnly: jsonData['dateOnly'],
    dayName: jsonData['dayName'],
    startTime: jsonData['startTime'],
    endTime: jsonData['endTime'],
    availability: jsonData['availability'],
   );
  }




  // ScadulesModel.fromJson(Map<String,dynamic>json)
  // {
  //  id = json['id'];
  //  dateOnly = json['dateOnly'];
  //  dayName = json['dayName'];
  //  startTime = json['startTime'];
  //  endTime = json['endTime'];
  //  availability = json['availability'];
  //
  // }
 }


 class Autogenerated {
  int? id;
  String? dateOnly;
  String? dayName;
  String? startTime;
  String? endTime;
  String? availability;

  Autogenerated(
      {this.id,
       this.dateOnly,
       this.dayName,
       this.startTime,
       this.endTime,
       this.availability});

  Autogenerated.fromJson(Map<String, dynamic> json) {
   id = json['id'];
   dateOnly = json['dateOnly'];
   dayName = json['dayName'];
   startTime = json['startTime'];
   endTime = json['endTime'];
   availability = json['availability'];
  }

  Map<String, dynamic> toJson() {
   final Map<String, dynamic> data = new Map<String, dynamic>();
   data['id'] = this.id;
   data['dateOnly'] = this.dateOnly;
   data['dayName'] = this.dayName;
   data['startTime'] = this.startTime;
   data['endTime'] = this.endTime;
   data['availability'] = this.availability;
   return data;
  }
 }